# Generated by Django 2.1.1 on 2018-09-09 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fifa', '0004_auto_20180908_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='league',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
