# Generated by Django 2.1.1 on 2018-09-10 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fifa', '0006_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1score', models.IntegerField()),
                ('p2score', models.IntegerField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifa.League')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='fifa.Player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='fifa.Player')),
            ],
        ),
    ]
