# Generated by Django 2.1.1 on 2018-09-18 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fifa', '0008_auto_20180916_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='record',
        ),
        migrations.RemoveField(
            model_name='player',
            name='league',
        ),
        migrations.AddField(
            model_name='player',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fifa.Record'),
        ),
    ]
